version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: prod-rabbitMq
    networks:
      - prod-network

  rest:
    container_name: prod-rest
    image: rest-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq

  token:
    container_name: prod-token
    image: token-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq

networks:
  prod-network: