version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: prod-rabbitMq
    networks:
      - prod-network

  rest:
    container_name: prod-rest
    image: rest-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    ports:
      - 8181:8181
    networks:
      - prod-network
    depends_on:
      - rabbitMq

  token:
    container_name: prod-token
    image: token-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq


  payment:
    container_name: prod-payment
    image: payment-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq

  account:
    container_name: prod-account
    image: account-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq

  report:
    container_name: prod-report
    image: report-service
    environment:
      - RABBIT_MQ_HOSTNAME=prod-rabbitMq
    networks:
      - prod-network
    depends_on:
      - rabbitMq


networks:
  prod-network:
